import { toHex } from "@midnight-ntwrk/midnight-js-utils";

/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

/**
 * Generates a random hex-encoded public key.
 */
export const randomCoinPublicKeyHex = (): string => {
  return toHex(randomBytes(32));
};

/**
 * Generates a random integer number > 0.
 */
export const randomNumber = (max: number | null): bigint => {
  return (
    BigInt(Math.floor(Math.random() * (max ? max : Number.MAX_SAFE_INTEGER))) +
    BigInt(1)
  );
};

/**
 * Generates a random integer number > 0 and < 256.
 */
export const randomRatingNumber = (): bigint => {
  return BigInt(Math.floor(Math.random() * 255)) + BigInt(1);
};
